<?php
include_once('OAuth.php');

//pesapal params
$token = $params = NULL;

/*
PesaPal Sandbox is at http://demo.pesapal.com. Use this to test your developement and 
when you are ready to go live change to https://www.pesapal.com.
*/
$consumer_key = '3TCZ7c3vQN5W50y8h39sHgxHFoqE0Vwt';//Register a merchant account on
                   //demo.pesapal.com and use the merchant key for testing.
                   //When you are ready to go live make sure you change the key to the live account
                   //registered on www.pesapal.com!
$consumer_secret ='5eO57BrgUIJs8E7hE8deZBvR8ko=';// Use the secret from your test
                   //account on demo.pesapal.com. When you are ready to go live make sure you 
                   //change the secret to the live account registered on www.pesapal.com!
$signature_method = new OAuthSignatureMethod_HMAC_SHA1();
$iframelink = 'https://www.pesapal.com/api/PostPesapalDirectOrderV4';//change to      
                   //https://www.pesapal.com/API/PostPesapalDirectOrderV4 when you are ready to go live!

//get form details
$amount =$price;
$amount = number_format($amount, 2);//format amount to 2 decimal places

$desc = "Good";
$type = "MERCHANT"; //default value = MERCHANT
$reference = "hjh";//unique order id of the transaction, generated by merchant
$first_name =$name;
// $last_name = "Dan";
$email = $email;
$phonenumber = $phone_number;//ONE of email or phonenumber is required

$callback_url = base_url().'index.php/home/home_load'; //redirect url, the page that will handle the response from pesapal.

$post_xml = "<?xml version=\"1.0\" encoding=\"utf-8\"?><PesapalDirectOrderInfo xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\" Amount=\"".$amount."\" Description=\"".$desc."\" Type=\"".$type."\" Reference=\"".$reference."\" FirstName=\"".$first_name."\"  Email=\"".$email."\" PhoneNumber=\"".$phonenumber."\" xmlns=\"http://www.pesapal.com\" />";
$post_xml = htmlentities($post_xml);

$consumer = new OAuthConsumer($consumer_key, $consumer_secret);

//post transaction to pesapal
$iframe_src = OAuthRequest::from_consumer_and_token($consumer, $token, "GET", $iframelink, $params);
$iframe_src->set_parameter("oauth_callback", $callback_url);
$iframe_src->set_parameter("pesapal_request_data", $post_xml);
$iframe_src->sign_request($signature_method, $consumer, $token);

//display pesapal - iframe and pass iframe_src
?> 
<iframe src="<?php echo $iframe_src;?>" width="50%" height="700px"  scrolling="no" frameBorder="0" style="margin-left:10em" position="absolute">
	<p>Browser unable to load iFrame</p>
</iframe>
<html>
   <div class="tickect_details_payment">
               
         <div class="inner_infor_ticket">
          Tickect Details
         </div> 

         <div class="holdtkdetails">
        
        <div class="tkheaders">Name:</div>
         <div class="tkelement_pay">
         <?php echo $name;?> 
         </div>

         <div class="tkheaders">Email</div>
         <div class="tkelement_pay">
         <?php echo $email;?>
         </div>

         <div class="tkheaders">Phone No.</div>
         <div class="tkelement_pay">
         <?php echo $phone_number;?>
          </div>

         <div class="tkheaders">Origin</div>
         <div class="tkelement_pay">

         <?php 
          
         echo $from;

         ?> 
         </div>
         <div class="tkheaders">Destination</div>
         <div class="tkelement_pay">

         <?php 
          
         echo $to;

         ?> 
         </div>

         <div class="tkheaders">Fare</div>
         <div class="tkelement_pay">

         <?php 
          $total_price= $count_result * $price;
         echo $total_price;

         ?> 
         </div>
         <div class="thanks">
             Thank You for booking with us
         </div>  
         </div>
         
     </div>


            <!-- page content -->
            <div class="page-content">
                
                <!-- page content wrapper -->
                <div class="page-content-wrap bg-img-1">

                    <div class="divider"><div class="box"><span class="fa fa-angle-down"></span></div></div>                    
                    
                    <!-- page content holder -->
                    <div class="page-content-holder">
                        
                        <div class="row">
                            <div class="col-md-5 this-animate" data-animate="fadeInLeft">
                                
                                <div class="block-heading block-heading-centralized">
                                    <h2 class="heading-underline">Book With Us, Save Some Cash</h2>
                                    <div class="block-heading-text">
                                        
                                    </div>
                                </div>
                                <div class="block this-animate" data-animate="fadeInLeft">
                                    <img src="<?php echo base_url();?>images/booking_image2.jpg" class="img-responsive"/>
                                </div>
                            </div>
                            
                            <div class="col-md-5 this-animate text-center" data-animate="fadeInRight">
                              <div class="block-heading block-heading-centralized">
                                  <h2 class="heading-underline">3 Easy Steps and you are ready to go!</h2>
                                  <div class="block-heading-text">
                                      
                                  </div>
                              </div>
                                <img  style = "height:" src="<?php echo base_url();?>/images/booking_process.jpg" class="img-responsive-mobile"/>
                            </div>
                        </div>
                        
                        
                        
                    </div>
                    <!-- ./page content holder -->
                    <div class="divider"><div class="box"><span class="fa fa-angle-down"></span></div></div>  
                </div>
                <!-- ./page content wrapper -->            
             </div>
            <!-- ./page content -->
            

</html>